development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url:  redis://redistogo:ba3cade73ace8a0689f021c754201909@pike.redistogo.com:10993/
  channel_prefix: message-me-app_production


#redis://redistogo:ba3cade73ace8a0689f021c754201909@pike.redistogo.com:10993/